### ISSUE TITLE
Out of subject

### ISSUE THREAD

**Issue by efkan** [daedroza/kernel_sony_apq8064#16]
Hello @daedroza,

I had installed your LinesageOS Yuga package about two months ago.

Unforunately, Settings -> Display -> LiveDisplay options never worked.

I wonder that do LiveDisplay options work in your latest compilation?

Sorry for inconvenience..

**Comment by daedroza** [comment]
Hi,
The issue lies in LineageOS trees. All other devices are affected too.
The intent of LiveDisplay is to work using Location Service (similar to what AOSP 8.x has done on NightDisplay).

> It is broken there & nobody has a proper "answer" to why it doesn't work correctly right now.

I keep LocationService active all the time, sometimes it changes to red tint & sometimes it doesn't.

NightDisplay from AOSP works fine though for some reason (but requires lot of GPS feedback than LiveDisplay).

We've two options, manually toggle LiveDisplay tile or you can add NightDisplay in overlays & that would bring you AOSP's NightDisplay.

Probable issue is [this change](https://github.com/AdrianDC/lineage_development_sony8960/commit/cac65b89721188e9873b0572b32b13bec81f0d76).

However it is reverted now, but still has issues. Rest assured, the kernel change was merged 2-3 years ago & the transition works fine from kernelspace :)

**Comment by efkan** [comment]
Thank you so much.

Keep up your awesome works!
